[package]
name = "builder-bees"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixed-buffer = "0.3.1"
array2d = "0.2.1"
enum-iterator = "0.7.0"
rand = "0.8.4"
pathfinding = "0.5.3"
